.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH paynal-init 1  "init " 
.SH NAME
paynal\-init \- Initialize a new Paynal workspace in the current directory
.SH SYNOPSIS
\fBpaynal init\fR [\fB\-n\fR|\fB\-\-name\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Initialize a new Paynal workspace in the current directory
.SH OPTIONS
.TP
\fB\-n\fR, \fB\-\-name\fR \fI<NAME>\fR
Project name (defaults to current folder name)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
