.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH paynal-mcp 1  "mcp " 
.SH NAME
paynal\-mcp \- Start Model Context Protocol (MCP) server mode for AI Agents
.SH SYNOPSIS
\fBpaynal mcp\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Start Model Context Protocol (MCP) server mode for AI Agents
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
