.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH paynal-ui 1  "ui " 
.SH NAME
paynal\-ui \- Launch interactive Terminal User Interface (TUI) dashboard
.SH SYNOPSIS
\fBpaynal ui\fR [\fB\-E\fR|\fB\-\-env\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Launch interactive Terminal User Interface (TUI) dashboard
.SH OPTIONS
.TP
\fB\-E\fR, \fB\-\-env\fR \fI<ENV>\fR
Environment profile (e.g. local, staging, prod)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
